#!/usr/bin/env bash

sfg_seeed_studio_j401_setup__set_up_seeed_studio_j401() {
    local username="${1}"

    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/scripts/common"
    source "${SCRIPT_DIR}/ssh_setup/setup"

    sfg_seeed_studio_j401_setup__check_environment "${1}" || exit 1
    sfg_ssh_setup__set_up_ssh

    local START_TEXT="> Setting up seeed studio J401."
    local END_TEXT="< Done setting up seeed studio J401."

    sfg_bash_utils__print_info "${START_TEXT}"

    # Source all scripts.
    for script in "${SCRIPT_DIR}/scripts"/*; do
        # shellcheck disable=SC1090
        source "${script}"
    done

    sfg_seeed_studio_j401_setup__update_packages
    sfg_seeed_studio_j401_setup__fix_intel_ax210
    sfg_seeed_studio_j401_setup__disable_wifi_power_management
    sfg_seeed_studio_j401_setup__install_dependencies "${username}"
    sfg_seeed_studio_j401_setup__set_up_vpi
    sfg_seeed_studio_j401_setup__set_max_performance 5
    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    sfg_seeed_studio_j401_setup__set_up_seeed_studio_j401 "${@}"
fi
