#!/usr/bin/env bash

sfg_seeed_studio_j401_setup__check_environment() {
    local username="${1}"

    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/common"

    if [[ -z "${username}" ]]; then
        sfg_bash_utils__print_error "Invalid invocation: ${*}"
        sfg_bash_utils__print_error "Usage: sudo $0 <username>"
        sfg_bash_utils__print_error "Example: sudo $0 ${USER}"
        return 1
    fi

    if ! getent passwd "${username}" >"/dev/null" 2>&1; then
        sfg_bash_utils__print_error "User '${username}' does not exist on the system."
        return 1
    fi

    if [ ! -f "/proc/device-tree/model" ] || ! grep -qi "nvidia jetson" "/proc/device-tree/model"; then
        sfg_bash_utils__print_error "This script is only meant to be executed on an NVIDIA Jetson platform."
        return 1
    fi

    if ! grep -q "R36 (release), REVISION: 4.0" "/etc/nv_tegra_release"; then
        sfg_bash_utils__print_error "This script is only meant to be executed on JetPack version 6.1."
        return 1
    fi

    if [[ -z "${SUDO_USER}" ]]; then
        sfg_bash_utils__print_error "Please run as root."
        return 1
    fi

    return 0
}
