#!/usr/bin/env bash

# Fix Intel AX210 WiFi chip not working. This approach is based on
#     - https://forum.seeedstudio.com/t/j4012-jetpack-6-no-wifi/279748/11
sfg_seeed_studio_j401_setup__fix_intel_ax210() {
    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/common"

    local START_TEXT="> Fixing Intel AX210 firmware."
    local END_TEXT="< Done fixing Intel AX210 firmware."

    sfg_bash_utils__print_info "${START_TEXT}"
    rm "/lib/modules/$(uname -r)/build"
    ln -s "/usr/src/linux-headers-$(uname -r)-ubuntu22.04_aarch64/3rdparty/canonical/linux-jammy/kernel-source" \
        "/lib/modules/$(uname -r)/build"
    apt install -y --no-install-recommends iwlwifi-modules
    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)/check_environment"
    sfg_seeed_studio_j401_setup__check_environment "${1}" || exit 1
    sfg_seeed_studio_j401_setup__fix_intel_ax210 "${@:2}"
fi
