#!/usr/bin/env bash

install_git_lfs() {
    local START_TEXT="> Installing Git LFS."
    local END_TEXT="< Done installing Git LFS."

    print_info "${START_TEXT}"
    apt-get install -y git-lfs
    git lfs install --skip-repo
    print_info "${END_TEXT}"
}

install_jtop() {
    local START_TEXT="> Installing jtop."
    local END_TEXT="< Done installing jtop."

    print_info "${START_TEXT}"
    apt install -y python3-pip
    pip3 install -U jetson-stats
    print_info "${END_TEXT}"
}

# Install Docker as described in
#     - https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository.
install_docker() {
    local username="${1}"

    local START_TEXT="> Installing Docker."
    local END_TEXT="< Done installing Docker."

    print_info "${START_TEXT}"
    apt-get update
    apt-get install -y ca-certificates curl
    install -m 0755 -d "/etc/apt/keyrings"
    curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" -o "/etc/apt/keyrings/docker.asc"
    chmod a+r "/etc/apt/keyrings/docker.asc"

    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by="/etc/apt/keyrings/docker.asc"] "https://download.docker.com/linux/ubuntu" \
        $(. "/etc/os-release" && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" |
        tee "/etc/apt/sources.list.d/docker.list" >"/dev/null"
    apt-get update

    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    groupadd docker
    usermod -aG docker "${username}"
    print_info "${END_TEXT}"
}

install_dependencies() {
    local username="${1}"

    install_git_lfs
    install_jtop
    install_docker "${username}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/common"
    check_environment "${1}" || exit 1
    install_dependencies "${@}"
fi
