#!/usr/bin/env bash

sfg_seeed_studio_j401_setup__install_git_lfs() {
    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/common"

    local START_TEXT="> Installing Git LFS."
    local END_TEXT="< Done installing Git LFS."

    sfg_bash_utils__print_info "${START_TEXT}"
    apt-get install -y git-lfs
    git lfs install --skip-repo
    sfg_bash_utils__print_info "${END_TEXT}"
}

sfg_seeed_studio_j401_setup__install_jtop() {
    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/common"

    local START_TEXT="> Installing jtop."
    local END_TEXT="< Done installing jtop."

    sfg_bash_utils__print_info "${START_TEXT}"
    apt install -y python3-pip
    pip3 install -U jetson-stats
    sfg_bash_utils__print_info "${END_TEXT}"
}

# Install Docker as described in
#     - https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository.
sfg_seeed_studio_j401_setup__install_docker() {
    local username="${1}"

    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/common"

    local START_TEXT="> Installing Docker."
    local END_TEXT="< Done installing Docker."

    sfg_bash_utils__print_info "${START_TEXT}"
    local docker_override_conf="/etc/systemd/system/docker.service.d/override.conf"
    mkdir -p "$(dirname "${docker_override_conf}")"

    cat <<-EOF >"${docker_override_conf}"
	[Service]
	# Fix for iptables raw issue on NVIDIA Jetson (https://forums.developer.nvidia.com/t/another-solution-with-iptables-raw-issue/328477).
	# Apparently not recommended for production environments (https://docs.docker.com/engine/release-notes/28/#networking-5) but we just
	# a bunch of amateurs anyways.
	Environment="DOCKER_INSECURE_NO_IPTABLES_RAW=1"
	EOF

    apt-get update
    apt-get install -y ca-certificates curl
    install -m 0755 -d "/etc/apt/keyrings"
    curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" -o "/etc/apt/keyrings/docker.asc"
    chmod a+r "/etc/apt/keyrings/docker.asc"

    # shellcheck disable=SC1091
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
        sudo tee "/etc/apt/sources.list.d/docker.list" > "/dev/null"
    apt-get update

    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    groupadd docker
    usermod -aG docker "${username}"
    sfg_bash_utils__print_info "${END_TEXT}"
}

sfg_seeed_studio_j401_setup__install_ntpdate() {
    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/common"

    local START_TEXT="> Installing ntpdate."
    local END_TEXT="< Done installing ntpdate."

    sfg_bash_utils__print_info "${START_TEXT}"
    apt-get install -y ntpdate
    sfg_bash_utils__print_info "${END_TEXT}"
}

sfg_seeed_studio_j401_setup__install_dependencies() {
    local username="${1}"

    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/common"

    sfg_seeed_studio_j401_setup__install_git_lfs
    sfg_seeed_studio_j401_setup__install_jtop
    sfg_seeed_studio_j401_setup__install_docker "${username}"
    sfg_seeed_studio_j401_setup__install_ntpdate
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)/check_environment"
    sfg_seeed_studio_j401_setup__check_environment "${1}" || exit 1
    sfg_seeed_studio_j401_setup__install_dependencies "${@}"
fi
