#!/usr/bin/env bash
print_color() {
    tput bold >&2
    tput setaf ${1} >&2
    print_plain "${2}"
    tput sgr0 >&2
}

print_error() {
    print_color 1 "${1}"
}

print_warning() {
    print_color 3 "${1}"
}

print_info() {
    print_color 2 "${1}"
}

print_plain() {
    echo "${1}" >&2
}
