#!/usr/bin/env bash

# Set max performance as decribed in
#     - https://nvidia-isaac-ros.github.io/getting_started/hardware_setup/compute/index.html#jetson-platforms
sfg_seeed_studio_j401_setup__set_max_performance() {
    local wait_in_seconds="${1}"

    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/common"

    local START_TEXT="> Setting max performance."
    local END_TEXT="< Done setting max performance. Rebooting in ${1} seconds."

    sfg_bash_utils__print_info "${START_TEXT}"
    jetson_clocks
    nvpmodel --force --wait "${wait_in_seconds}" --mode 0
    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)/check_environment"
    sfg_seeed_studio_j401_setup__check_environment "${1}" || exit 1
    sfg_seeed_studio_j401_setup__set_max_performance "${@:2}"
fi
