#!/usr/bin/env bash

# Set up VPI as described in
#     - https://nvidia-isaac-ros.github.io/getting_started/hardware_setup/compute/jetson_vpi.html
sfg_seeed_studio_j401_setup__set_up_vpi() {
    local SCRIPT_DIR
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)"
    source "${SCRIPT_DIR}/common"

    local START_TEXT="> Setting up VPI."
    local END_TEXT="< Done setting up VPI."

    sfg_bash_utils__print_info "${START_TEXT}"
    nvidia-ctk cdi generate --mode=csv --output=/etc/cdi/nvidia.yaml

    apt update
    apt install software-properties-common
    apt-key adv --fetch-key "https://repo.download.nvidia.com/jetson/jetson-ota-public.asc"
    add-apt-repository -y 'deb https://repo.download.nvidia.com/jetson/common r36.4 main'
    apt update
    apt install -y pva-allow-2
    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -e
    source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)/check_environment"
    sfg_seeed_studio_j401_setup__check_environment "${1}" || exit 1
    sfg_seeed_studio_j401_setup__set_up_vpi "${@:2}"
fi
