#!/usr/bin/env bash

# Keep apt from upgrading L4T packages and then update, upgrade, and autoremove packages as described in
#     - https://www.forecr.io/blogs/bsp-development/how-to-apply-distro-upgrade-apt-upgrade-on-jetson-modules
sfg_seeed_studio_j401_setup__update_packages() {
    local SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/common"

    local START_TEXT="> Updating apt packages."
    local END_TEXT="< Done updating apt packages."

    sfg_bash_utils__print_info "${START_TEXT}"
    apt-mark hold 'nvidia-l4t-*'
    apt-get update
    apt-get upgrade -y
    apt-get autoremove -y
    sfg_bash_utils__print_info "${END_TEXT}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)/check_environment"
    sfg_seeed_studio_j401_setup__check_environment "${1}" || exit 1
    sfg_seeed_studio_j401_setup__update_packages "${@:2}"
fi
